# -*- coding: utf-8 -*-
"""
Django settings for students project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from django.conf import global_settings
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY! WARNING: don't run with debug turned on in production
DEBUG = True

ALLOWED_HOSTS = ['students.sharelink.ru']#'students.sharelink.ru   localhost'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'student',
    'crispy_forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'students.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 os.path.join(BASE_DIR, 'student/templates',)
                 ]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'students.contex_processors.students_proc',
                'student.context_processors.groups_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'students.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")


# Путь до папки со статическими файлами (Работает и без этой настройки!)
STATICFILES_DIRS = (
    # ('static', 'D:/OpenServer/domains/mysite/static/'),
    os.path.join(BASE_DIR, 'student/static'), # Путь для копирование файлов из каталога blog/static в основной каталог статики!
    #os.path.join(BASE_DIR, 'page/static'), # Путь для копирование файлов из каталога blog/static в основной каталог статики!
    # 'D:/OpenServer/domains/mysite/static/bootstrap',
)


# Посик статических файлов во всех папках и разделах
# https://docs.djangoproject.com/en/1.8.6/ref/settings/
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    # other finders..
    #'compressor.finders.CompressorFinder', # Относится к Django Compressor

)

PORTAL_URL = 'http://127.0.0.1:8000'

# Настройки почтового сервера
#ADMIN_EMAIL = 'atari1971@mail.ru'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_HOST_USER = 'blazer-05@mail.ru'
EMAIL_HOST_PASSWORD = 'mypassword'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = 'blazer-05@mail.ru'
#EMAIL_USE_TLS = True
#SERVER_EMAIL = 'blazer-05@mail.ru'
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

CRISPY_TEMPLATE_PACK = 'bootstrap3'

# Замена заголовка входа в админку на свой и замена тайтла
from django.contrib import admin
admin.site.site_header = 'Привет админ!'
admin.site.site_title = 'Студенты'
