# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='\u0418\u043c\u044f')),
                ('last_name', models.CharField(max_length=256, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('middle_name', models.CharField(max_length=256, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('birthday', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('photo', models.ImageField(blank=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e')),
                ('ticket', models.CharField(max_length=256, verbose_name='\u0411\u0438\u043b\u0435\u0442')),
                ('notes', models.TextField(blank=True, verbose_name='\u041e\u0441\u043e\u0431\u044b\u0435 \u043e\u0442\u043c\u0435\u0442\u043a\u0438')),
            ],
        ),
    ]
