# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.Group', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430'),
        ),
    ]
