# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-26 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20180120_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name=b'title')),
                ('privacy', models.TextField(blank=True, verbose_name=b'privacy')),
            ],
            options={
                'verbose_name': 'Privacy',
            },
        ),
    ]
